### ISSUE TITLE
NCR overflow on Province, atbp ie NE; Not custom Stylable 

### ISSUE THREAD

**Issue by jdtenoso** [josephmangmang/philippines_rpcmb#1]
NCR -> province text overflow caused by long text ie 'NATIONAL CAPITAL REGION...MANILA ect', too long for phone displays and dropdowns.

NOT STYLEABLE.... should have entry point to decorate the dropdown and also to style the Text() in every RPCMB dropdowns.

please fix, thanks and best regards

**Comment by josephmangmang** [comment]
Hi, done fixing. Please upgrade to v0.0.3

**Comment by josephmangmang** [comment]
Hi, done fixing please upgrade to v0.0.3 Thanks

**Comment by jdtenoso** [comment]
thanks for fixing, love this package, my nickname is also Joseph, katokayo haha. Best Regards.
